<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXI8hgxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXI8hgxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXI8hgxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXI8hgxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXI8hgxF\App_KernelDevDebugContainer([
    'container.build_hash' => 'XI8hgxF',
    'container.build_id' => '83e20b1d',
    'container.build_time' => 1678817625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXI8hgxF');
